### ISSUE TITLE
Ring oscillator inverter

### ISSUE THREAD

**Issue by DurandA** [dpiegdon/ringoscillator#1]
I noticed that you used an initialization value of `16'd2` = `16'b0000_0000_0000_0010` for the inverter of the ring oscillator:
https://github.com/dpiegdon/ringoscillator/blob/0d3cfdbe4d208f780dfe87b879d85bf288099eb7/ringoscillator.v#L9
This is the *SB_LUT4* table from *SiliconBlue ICE Technology Library* documentation:
![lut4](https://user-images.githubusercontent.com/3709037/52515173-87299f80-2c18-11e9-9c09-1ba22bf3040d.png)

Using initialization values of `I1=0`, `I2=0` and `I3=0`, we can reduce the table to:

| IO | O           |
|----|-------------|
| 0  | LUT_INIT[0] |
| 1  | LUT_INIT[1] |

Shouln't be this *SB_LUT4* table initialized with `16'd1`? I think that this LUT is acting as a delay rather than an inverter. I also noticed than the IceStorm author @cliffordwolf did the same in his original example so I am probably missing something.

Btw, thank you for sharing your experiments with ring oscillators!

**Comment by dpiegdon** [comment]
the inversion is actually done not in the LUT but in general logic:  

`
    assign chain_in = !chain_out;
`

the LUT is only working as a delay line here, and to make sure the compiler is not removing the logic.
when you only use the line above, all is removed, as mentioned in the ticket description of https://github.com/YosysHQ/yosys/issues/804 .
I also tried only using a LUT with 16'h1 as init value, but that either did not work, or the output VPP of the oscillator was so low, that I could not measure it. but the logic *was* in the ASC file. I checked on the ice40-viewer and in the nextpnr-gui.

**Comment by dpiegdon** [comment]
> Btw, thank you for sharing your experiments with ring oscillators!

a pleasure! great to know that this is of use to someone else :)

**Comment by dpiegdon** [comment]
sorry, I am wrong. my oscilloscope could not see the signal, but my spectrum analyzer actually does.
i can see a -25dBm peak at roughly 625 MHz. no wonder my cheap rigol could not see it :).
but the signal is so weak, it might be useless. -25 dBm is 35.560 mVpp. so even internal logic using the oscillator may not properly work, even though it will be stronger in the internal logic.
so I think putting in a single-LUT delay is a good choice here.

**Comment by DurandA** [comment]
> the inversion is actually done not in the LUT but in general logic:
> 
> `assign chain_in = !chain_out;`

Wow, I completely missed the `!` in `assign chain_in = resetn ? !chain_out : 0;` from original implementation. Thanks for the clarification.

**Comment by DurandA** [comment]
> > Btw, thank you for sharing your experiments with ring oscillators!
> 
> a pleasure! great to know that this is of use to someone else :)

I want to add a TRNG to [picosoc](https://github.com/cliffordwolf/picorv32) as an exercise. I am completely new to FPGAs and digital design.

**Comment by DurandA** [comment]
> sorry, I am wrong. my oscilloscope could not see the signal, but my spectrum analyzer actually does.
> i can see a -25dBm peak at roughly 625 MHz. no wonder my cheap rigol could not see it :).
> but the signal is so weak, it might be useless. -25 dBm is 35.560 mVpp. so even internal logic using the oscillator may not properly work, even though it will be stronger in the internal logic.
> so I think putting in a single-LUT delay is a good choice here.

Thanks for sharing this. I will do some more experiments with [manually placed](https://github.com/YosysHQ/nextpnr/blob/master/docs/constraints.md#absolute-placement-constraints) inverter LUTs. I only have an Analog Discovery 2 as an oscilloscope so I will probably need to fill at least two tiles with LUTs to see the signal. I will report back my results here.

**Comment by dpiegdon** [comment]
> I want to add a TRNG to [picosoc](https://github.com/cliffordwolf/picorv32) as an exercise. I am completely new to FPGAs and digital design.

Actually thats a really neat project!
If you want to have a good randomness, starting with randomized_lfsr16 or at least the destabilizer in it might be a good idea - maybe with a larger LFSR, say >32 bits for the 32bit risc. The destabilizer output looks pretty metastable on a scope and spectrum analyzer, so its a good start. It has potential for improvement though (see the papers I referenced in the yosys ticket).
Thats what I am looking into in my spare time here. If you come up with something neat, I'd be glad if you let me know!
